### ISSUE TITLE
Missing natBib Cite

### ISSUE THREAD

**Issue by FRautenberg** [mathisheeren/latex-for-students#3]
.bib file is empty
Please add an working example for citation

**Comment by mathisheeren** [comment]
Hello thanks for your suggestion. 
The .bib file should be empty to be able to make entries there without having to delete anything first.

I will upload example code on another branch.

**Comment by mathisheeren** [comment]
I have created a new branch "example-code" that contains a working example. 
I will close this bug now.
Thank you for your suggestion.

**Comment by mathisheeren** [comment]
I have created a new branch "example-code" that contains a working example. I hope it helps you.
I will close this bug now.
Thank you for your suggestion
